Footer html
vitor-chaves-lima/dom-agnello-landing-page pull request #2
Opened 2024-04-23 22:49 UTC by matheusmarcelino1

2024-04-23 23:08 UTC, vitor-chaves-lima requested changes

2024-04-23 23:08 UTC, vitor-chaves-lima commented on index.html
> +    <title>Footer</title>
Título incorreto, voltar texto anterior:

Dom Agnello

2024-04-23 23:08 UTC, vitor-chaves-lima commented on index.html
> +</footer>
O footer fica dentro da estrutura do body

2024-04-23 23:08 UTC, vitor-chaves-lima commented on index.html
> +           Loja</p>
Esse conteúdo deve ser uma ul

2024-04-23 23:08 UTC, vitor-chaves-lima commented on index.html
> +    </div>
Não precisamos dessa div

2024-04-23 23:08 UTC, vitor-chaves-lima commented on style.css
> +.texto {
Remover o **width** fixo

2024-04-24 03:23 UTC, vitor-chaves-lima requested changes

2024-04-24 03:23 UTC, vitor-chaves-lima commented on index.html
> +    <script src="script.js"></script>
Remove esse código javascript

2024-04-24 03:23 UTC, vitor-chaves-lima commented on index.html
> +        <div class="text">
Muda o nome da classe, pode colocar **site-map**

2024-04-24 03:23 UTC, vitor-chaves-lima commented on index.html
> +        <div class="text1">
Muda o nome da classe, pode colocar **copyright**

2024-04-24 13:42 UTC, matheusmarcelino1 commented on index.html
> +        <div class="text">
no lugar do text ou do container?

2024-04-24 14:36 UTC, vitor-chaves-lima commented on index.html
> +        <div class="text">
Do text

2024-04-24 14:58 UTC, vitor-chaves-lima approved these changes

2024-04-24 15:25 UTC, vitor-chaves-lima approved these changes

2024-04-24 15:25 UTC, merged